# Generated by Django 4.2 on 2023-10-24 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_product_image_product_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productimage',
            new_name='product_image',
        ),
    ]
